server:
  port: 8084
  ssl:
    enabled: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: deekul
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message

bot:
  name: fileshr_bot
  token:
  uri:


