server:
  port: ${NODE_PORT:8085}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5673}
    username: ${RABBIT_USERNAME:deekul}
    password: ${RABBIT_PASSWORD:p@ssw0rd}
    queues:
      text-message-update: ${RABBIT_TEXT_MESSAGE_UPDATE_QUEUE}
      doc-message-update: ${RABBIT_DOC_MESSAGE_UPDATE_QUEUE}
      photo-message-update: ${RABBIT_PHOTO_MESSAGE_UPDATE_QUEUE}
      answer-message: ${RABBIT_ANSWER_MESSAGE_QUEUE}
      registration-mail: ${RABBIT_REGISTRATION_MAIL_QUEUE}
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:9100/fileSharingDb}
    username: ${POSTGRES_USERNAME:deekul}
    password: ${POSTGRES_PASSWORD:p@ssw0rd}
  jpa:
    generate-ddl: true

token: ${TG_BOT_TOKEN}
service:
  file_info:
    uri: ${TG_BOT_FILE_INFO_URI}
  file_storage:
    uri: ${TG_BOT_FILE_STORAGE_URI}

link:
  address: ${TG_BOT_URI:http://localhost:8086}
salt: ${SALT:test}